In [110]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns

In [111]:
orders= pd.read_csv("Ecommerce_website/orders.csv", encoding='latin-1') 
orders.head()

    order_id  user_id                  order_date order_status  total_amount
0  O00000001  U009310  2025-09-09T14:52:37.292731   processing        689.66
1  O00000002  U003247  2025-04-15T01:18:27.193404    completed       1666.85
2  O00000003  U007252  2025-04-27T15:37:48.008624   processing        665.06
3  O00000004  U008986  2025-10-04T20:35:22.204857    cancelled        689.50
4  O00000005  U008537  2024-11-13T08:15:18.498252    cancelled        860.50

In [112]:
reviews = pd.read_csv("Ecommerce_website/reviews.csv", encoding='latin-1') 
reviews.head()

,review_id,order_id,product_id,user_id,rating,review_text,review_date
0,R00000528,O00000237,P001326,U001094,2,Color was different from images.,2025-10-14T12:03:56.749446
1,R00005792,O00002627,P000329,U001858,4,Highly recommend this brand.,2024-10-09T08:04:50.171793
2,R00036604,O00016798,P001160,U008109,4,Highly recommend this brand.,2024-06-03T05:11:16.787214
3,R00040163,O00018414,P001427,U006835,5,Highly recommend this brand.,2024-02-12T06:41:50.215810
4,R00031127,O00014300,P001639,U007148,3,Item arrived damaged.,2025-01-20T05:32:09.398860

In [ ]:
users= pd.read_csv("Ecommerce_website/users.csv", encoding='latin-1') 
users.head()

In [ ]:
products = pd.read_csv("Ecommerce_website/products.csv", encoding='latin-1') 
products.head()

In [ ]:
order_items = pd.read_csv("Ecommerce_website/order_items.csv", encoding='latin-1') 
order_items.head()

In [ ]:
events= pd.read_csv("Ecommerce_website/events.csv", encoding='latin-1') 
events.head()

In [ ]:
orders.describe()

In [ ]:
reviews.describe()

In [ ]:
users.describe()

In [ ]:
products.describe()

In [ ]:
order_items.describe()

In [ ]:
events.describe()

In [ ]:
orders.info()

In [ ]:
reviews.info()

In [ ]:
users.info()

In [ ]:
products.info()

In [ ]:
order_items.info()

In [ ]:
events.info()

# Convert date column

In [ ]:
orders['order_date'] = pd.to_datetime(orders['order_date'])
reviews['review_date'] = pd.to_datetime(reviews['review_date'])
events['event_timestamp'] = pd.to_datetime(events['event_timestamp'])

# Adding new column like month,year and dayofweek

In [ ]:
orders['Order_Month'] = orders['order_date'].dt.month 
orders['Order_Year'] = orders['order_date'].dt.year
orders['Order_Day_of_Week'] = orders['order_date'].dt.dayofweek
reviews['Order_Month'] = reviews['review_date'].dt.month 
reviews['Order_Year'] = reviews['review_date'].dt.year
reviews['Order_Day_of_Week'] = reviews['review_date'].dt.dayofweek
events['Order_Month'] = events['event_timestamp'].dt.month 
events['Order_Year'] = events['event_timestamp'].dt.year
events['Order_Day_of_Week'] =events['event_timestamp'].dt.dayofweek

# Total Revenue using order_items table

In [ ]:
total_revenue = order_items["item_total"].sum()

print("Total Revenue:", total_revenue)

# Average amount spent per order.

In [ ]:
avg_order_value = orders["total_amount"].mean()

print("Average Order Value:", avg_order_value)

# Order Status Distribution

In [ ]:

status_counts = orders["order_status"].value_counts()

print(status_counts)

status_counts.plot(kind="bar")
plt.title("Order Status Distribution")
plt.show()

# Monthly Order Trend

In [ ]:
orders["order_date"] = pd.to_datetime(orders["order_date"])

monthly_orders = orders.groupby(
    orders["order_date"].dt.to_period("M")
).size()

monthly_orders.plot()
plt.title("Monthly Order Trend")
plt.ylabel("Orders")
plt.show()

# Top Selling Products

In [ ]:
df = pd.merge(order_items, products, on="product_id")

top_products = df.groupby("product_name")["quantity"].sum().sort_values(ascending=False).head(10)

print(top_products)

In [ ]:
top_products.plot(kind="bar")
plt.title("Top Selling Products")
plt.ylabel("Units Sold")
plt.show()

# Revenue by Category

In [ ]:
category_revenue = df.groupby("category")["item_total"].sum().sort_values(ascending=False)

print(category_revenue)

In [ ]:
category_revenue.plot(kind="bar")
plt.title("Revenue by Category")
plt.show()

# Customer Purchase Frequency

In [ ]:
purchase_freq = orders.groupby("user_id")["order_id"].count()

print(purchase_freq.describe())

In [ ]:
purchase_freq.hist(bins=20)
plt.title("Customer Purchase Frequency")
plt.show()

# Top Customers by Spending

In [ ]:
customer_spending = orders.groupby("user_id")["total_amount"].sum().sort_values(ascending=False).head(10)

print(customer_spending)

# Funnel Analysis (Views → Cart)

In [ ]:
funnel = events["event_type"].value_counts()

print(funnel)

In [ ]:
funnel.plot(kind="bar")
plt.title("User Funnel Events")
plt.show()

# User Engagement (Active vs inactive users)

In [ ]:
user_activity = events.groupby("user_id")["event_type"].count()

user_activity.hist(bins=30)
plt.title("User Engagement Distribution")
plt.show()

# Rating Distribution (Customer satisfaction levels)

In [ ]:
rating_counts = reviews["rating"].value_counts().sort_index()

print(rating_counts)

# Average Rating per Product

In [ ]:
avg_rating = reviews.groupby("product_id")["rating"].mean().sort_values(ascending=False).head(10)

print(avg_rating)

# Revenue by Brand (Brands generating most revenue)

In [ ]:
brand_revenue = df.groupby("brand")["item_total"].sum().sort_values(ascending=False)

print(brand_revenue.head(10))

# Customer Segmentation (A small group of high-value customers contributes significantly to revenue)

In [ ]:
customer_spending = orders.groupby("user_id")["total_amount"].sum()

segments = pd.qcut(customer_spending, q=3, labels=["Low Value", "Medium Value", "High Value"])

segment_counts = segments.value_counts()

segment_counts.plot(kind="bar")
plt.title("Customer Segmentation")
plt.show()

# City-wise Customer Distribution

In [ ]:
city_users = users["city"].value_counts().head(10)

city_users.plot(kind="bar")
plt.title("Top Cities by Number of Users")
plt.show()

# Analyze Cancelled Orders

In [ ]:
cancel_rate = orders["order_status"].value_counts(normalize=True) * 100

print(cancel_rate)

# Product Rating vs Sales Analysis(Higher-rated products tend to sell more)

In [ ]:
sales_rating = df.groupby("product_id").agg({
    "quantity":"sum",
    "rating":"mean"
})

print(sales_rating.head())

# Product Price vs Rating(Higher priced products do not always have better ratings)

In [ ]:


sns.scatterplot(data=products, x="price", y="rating")

plt.title("Product Price vs Rating")
plt.show()